# Generated by Django 4.1.6 on 2023-03-09 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
            ],
        ),
    ]
