# Generated by Django 4.1.6 on 2023-03-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casetype',
            fields=[
                ('casetypeid', models.AutoField(primary_key=True, serialize=False)),
                ('casetype', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
    ]
