# Generated by Django 4.1.6 on 2023-04-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0006_delete_casetype_remove_location_districtid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casetype',
            fields=[
                ('casetypeid', models.AutoField(primary_key=True, serialize=False)),
                ('casetype', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtid', models.AutoField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('locationname', models.CharField(max_length=50)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
            ],
        ),
    ]
