# Generated by Django 4.1.6 on 2023-03-17 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0003_casetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('advocateid', models.AutoField(primary_key=True, serialize=False)),
                ('advocatename', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('license', models.CharField(max_length=150)),
                ('experience', models.BigIntegerField()),
                ('licensenumber', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
            ],
        ),
    ]
