# Generated by Django 4.1.6 on 2023-03-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0002_remove_advocate_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='license',
            field=models.ImageField(default='a', upload_to=''),
            preserve_default=False,
        ),
    ]
