# Generated by Django 4.1.6 on 2023-03-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0003_advocate_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
            ],
        ),
    ]
