# Generated by Django 4.1.6 on 2023-03-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0004_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='status',
            field=models.CharField(default=2, max_length=150),
            preserve_default=False,
        ),
    ]
