# Generated by Django 4.1.6 on 2023-03-18 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_casetype'),
        ('guestapp', '0005_login_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=150)),
                ('pincode', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.CharField(max_length=150)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login')),
            ],
        ),
    ]
