# Generated by Django 4.1.6 on 2023-03-20 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_casetype'),
        ('guestapp', '0006_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('casedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('casetitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('requeststatus', models.CharField(max_length=150)),
                ('filedetails', models.FileField(upload_to='')),
                ('amount', models.BigIntegerField()),
                ('submitedate', models.DateField()),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
    ]
