# Generated by Django 4.1.6 on 2023-03-20 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0007_casedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetails',
            name='submitedate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
