# Generated by Django 4.1.6 on 2023-03-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0008_alter_casedetails_submitedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
