# Generated by Django 4.1.6 on 2023-04-12 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0005_initial'),
        ('guestapp', '0010_remove_casedetails_advocateid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('advocateid', models.AutoField(primary_key=True, serialize=False)),
                ('advocatename', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('license', models.ImageField(upload_to='')),
                ('experience', models.BigIntegerField()),
                ('licensenumber', models.BigIntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=150)),
                ('pincode', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.CharField(max_length=150)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('casedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('casetitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('requeststatus', models.CharField(max_length=150)),
                ('filedetails', models.FileField(upload_to='')),
                ('amount', models.BigIntegerField()),
                ('submitedate', models.DateField(default=datetime.date.today)),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
    ]
