# Generated by Django 4.1.6 on 2023-04-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('sittingid', models.AutoField(primary_key=True, serialize=False)),
                ('sittingamount', models.BigIntegerField()),
                ('submitedate', models.DateField()),
                ('sittingdescription', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='password',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='username',
        ),
        migrations.AddField(
            model_name='advocate',
            name='loginid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='guestapp.login'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SittingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdescription', models.CharField(max_length=150)),
                ('paymentdate', models.DateField()),
                ('paymentstatus', models.CharField(max_length=150)),
                ('sittingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.sitting')),
            ],
        ),
        migrations.AddField(
            model_name='sitting',
            name='advocateid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='casedetailsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.casedetails'),
        ),
        migrations.AddField(
            model_name='sitting',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client'),
        ),
        migrations.CreateModel(
            name='Casestatus',
            fields=[
                ('casestatusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(max_length=150)),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
    ]
