# Generated by Django 4.1.6 on 2023-04-12 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0007_initial'),
        ('guestapp', '0013_remove_casedetails_advocateid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('advocateid', models.AutoField(primary_key=True, serialize=False)),
                ('advocatename', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='images/')),
                ('license', models.ImageField(upload_to='')),
                ('experience', models.BigIntegerField()),
                ('licensenumber', models.BigIntegerField()),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Casedetails',
            fields=[
                ('casedetailsid', models.AutoField(primary_key=True, serialize=False)),
                ('casetitle', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('requeststatus', models.CharField(max_length=150)),
                ('filedetails', models.FileField(upload_to='')),
                ('amount', models.BigIntegerField()),
                ('submitedate', models.DateField(default=datetime.date.today)),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('casetypeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.casetype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('clientname', models.CharField(max_length=50)),
                ('housename', models.CharField(max_length=150)),
                ('pincode', models.BigIntegerField()),
                ('emailid', models.CharField(max_length=150)),
                ('contactnumber', models.CharField(max_length=150)),
                ('districtid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.district')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.location')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('loginid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Sitting',
            fields=[
                ('sittingid', models.AutoField(primary_key=True, serialize=False)),
                ('sittingamount', models.BigIntegerField()),
                ('submitedate', models.DateField()),
                ('sittingdescription', models.CharField(max_length=150)),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('casedetailsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.casedetails')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='SittingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdescription', models.CharField(max_length=150)),
                ('paymentdate', models.DateField()),
                ('paymentstatus', models.CharField(max_length=150)),
                ('sittingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.sitting')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login'),
        ),
        migrations.CreateModel(
            name='Casestatus',
            fields=[
                ('casestatusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(max_length=150)),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='casedetails',
            name='clientid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='loginid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.login'),
        ),
    ]
