# Generated by Django 4.1.6 on 2023-04-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guestapp', '0014_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('casestatusid', models.AutoField(primary_key=True, serialize=False)),
                ('statusdescription', models.CharField(max_length=150)),
                ('updateddate', models.DateField()),
                ('nextdate', models.DateField()),
                ('advocateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.advocate')),
                ('casedetailsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.casedetails')),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guestapp.client')),
            ],
        ),
        migrations.DeleteModel(
            name='Casestatus',
        ),
    ]
